START TRANSACTION;

ALTER TABLE "LocationHistories"
ADD COLUMN IF NOT EXISTS "ClientLocalId" text;

CREATE TABLE IF NOT EXISTS "DeviceRecoveryEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviceId" integer NOT NULL,
    "EngineerId" integer NOT NULL,
    "RecoveryReason" text NOT NULL,
    "FromUtc" timestamp with time zone,
    "ToUtc" timestamp with time zone,
    "UploadedPointsCount" integer NOT NULL,
    "DroppedPointsCount" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "PublicId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_DeviceRecoveryEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeviceRecoveryEvents_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeviceRecoveryEvents_Engineers_EngineerId" FOREIGN KEY ("EngineerId") REFERENCES "Engineers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_LocationHistories_DeviceId_ClientLocalId"
ON "LocationHistories" ("DeviceId", "ClientLocalId")
WHERE "ClientLocalId" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_DeviceRecoveryEvents_DeviceId"
ON "DeviceRecoveryEvents" ("DeviceId");

CREATE INDEX IF NOT EXISTS "IX_DeviceRecoveryEvents_EngineerId"
ON "DeviceRecoveryEvents" ("EngineerId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeviceRecoveryEvents_PublicId"
ON "DeviceRecoveryEvents" ("PublicId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260630152953_AddOfflineBatchTrackingAndDiagnostics', '10.0.9'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260630152953_AddOfflineBatchTrackingAndDiagnostics'
);

COMMIT;