START TRANSACTION;
ALTER TABLE "AspNetUsers" DROP CONSTRAINT "FK_AspNetUsers_Engineers_EngineerId";

DROP INDEX "IX_AspNetUsers_EngineerId";

ALTER TABLE "Engineers" ADD "UserId" uuid;

ALTER TABLE "AspNetUsers" ADD "UserType" text;


DO $$
BEGIN
    -- Check for users with multiple roles
    IF EXISTS (
        SELECT 1 FROM "AspNetUserRoles"
        GROUP BY "UserId"
        HAVING COUNT("RoleId") > 1
    ) THEN
        RAISE EXCEPTION 'Migration failed: Detected users with multiple roles in AspNetUserRoles. Manual cleanup is required.';
    END IF;

    -- Check for active users with no roles
    IF EXISTS (
        SELECT 1 FROM "AspNetUsers" u
        LEFT JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
        WHERE ur."UserId" IS NULL AND u."IsDeleted" = FALSE
    ) THEN
        RAISE EXCEPTION 'Migration failed: Detected active users with no assigned role. Manual cleanup is required.';
    END IF;

    -- Check for Engineer role users without Engineer profile link
    IF EXISTS (
        SELECT 1 FROM "AspNetUsers" u
        JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
        JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
        WHERE r."Name" = 'Engineer' AND u."EngineerId" IS NULL
    ) THEN
        RAISE EXCEPTION 'Migration failed: Detected Engineer role users without an Engineer profile link (EngineerId is null).';
    END IF;
END $$;



UPDATE "AspNetUsers" u
SET "UserType" = r."Name"
FROM "AspNetUserRoles" ur
JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
WHERE u."Id" = ur."UserId";



DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM "AspNetUsers"
        WHERE "UserType" IS NULL AND "IsDeleted" = FALSE
    ) THEN
        RAISE EXCEPTION 'Migration failed: Some active users do not have a UserType after backfilling.';
    END IF;
END $$;


ALTER TABLE "AspNetUsers" ALTER COLUMN "UserType" SET NOT NULL;

CREATE TABLE "Admins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "FullName" text NOT NULL,
    "Email" text,
    "PhoneNumber" text,
    "PublicId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Admins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Managers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "FullName" text NOT NULL,
    "Email" text,
    "PhoneNumber" text,
    "PublicId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Managers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Managers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


INSERT INTO "Admins" ("PublicId", "UserId", "FullName", "Email", "CreatedAt", "IsDeleted")
SELECT gen_random_uuid(), u."Id", u."FullName", u."Email", NOW(), FALSE
FROM "AspNetUsers" u
JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
WHERE r."Name" = 'Admin'
  AND NOT EXISTS (SELECT 1 FROM "Admins" a WHERE a."UserId" = u."Id");

INSERT INTO "Managers" ("PublicId", "UserId", "FullName", "Email", "CreatedAt", "IsDeleted")
SELECT gen_random_uuid(), u."Id", u."FullName", u."Email", NOW(), FALSE
FROM "AspNetUsers" u
JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
WHERE r."Name" = 'Manager'
  AND NOT EXISTS (SELECT 1 FROM "Managers" m WHERE m."UserId" = u."Id");



UPDATE "Engineers" e
SET "UserId" = u."Id"
FROM "AspNetUsers" u
WHERE e."Id" = u."EngineerId" AND e."UserId" IS NULL;


CREATE UNIQUE INDEX "IX_Engineers_UserId" ON "Engineers" ("UserId") WHERE "UserId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_AspNetUsers_EngineerId" ON "AspNetUsers" ("EngineerId") WHERE "EngineerId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Admins_PublicId" ON "Admins" ("PublicId");

CREATE UNIQUE INDEX "IX_Admins_UserId" ON "Admins" ("UserId");

CREATE UNIQUE INDEX "IX_Managers_PublicId" ON "Managers" ("PublicId");

CREATE UNIQUE INDEX "IX_Managers_UserId" ON "Managers" ("UserId");

CREATE UNIQUE INDEX "IX_AspNetUserRoles_UserId" ON "AspNetUserRoles" ("UserId");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Engineers_EngineerId" FOREIGN KEY ("EngineerId") REFERENCES "Engineers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Engineers" ADD CONSTRAINT "FK_Engineers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260630184628_AddUserProfilesAndSingleRoleConstraint', '10.0.9');

COMMIT;

