export const routes = {
  login: '/login',
  dashboard: '/dashboard',
  engineers: '/engineers',
  devices: '/devices',
  assignments: '/assignments',
  deviceRequests: '/device-requests',
  liveMap: '/live-map',
  chat: '/chat',
  emails: '/emails',
  auditLogs: '/audit-logs',
  appUpdates: '/app-updates',
  profile: '/profile',
  managers: '/managers',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
};